# config context path to "/" by setting an empty string
server:
  port: 8082
  servlet:
    context-path: /api

# JACKSON
spring:
  main:
    allow-circular-references: true

  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    ## MYSQL
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_5d5475fb76dbd91
    username: bd845ddf008a8a
    password: 558ee23b
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: none

jwt:
  header: Authorization
  secret: logiticsSecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh